version: '3.9'

services:
  api:
    build:
      context: ./python 
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000 
    networks:
      - mercari-network

  frontend:
    build:
      context: ./typescript/simple-mercari-web  
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000 
    depends_on:
      - api
    networks:
      - mercari-network

networks:
  mercari-network:
    driver: bridge